[package]
name = "prols_router"
type = "contract"
authors = [""]
compiler_version = ">=0.34.0"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.55.1", directory = "noir-projects/aztec-nr/aztec" }
token = { path = "../token" }
